### PR TITLE
E-974 fix: add checking for not uploaded docs

### PR DESCRIPTION
**Pull request by dudiq**

### CODE REVIEW

**Comment by dudiq** [comment]
@lamartire ready for review

**Comment by ifiri** [comment]
@dudiq in general it works, I see `required docs` after upload instead continue. But, when you upload document, in `required docs` screen you still see `not uploaded` status, when should be `pending review`, Correct status appears when you close and open modal.

Details on video: https://drive.google.com/file/d/1wAsB3qKCOSJ5RYISA8g9YDPiuarD-71d/view

**Comment by dudiq** [comment]
@ifiri fixed, check again

**Comment by ifiri** [comment]
@kazurus approved

**Pull request merged**
