### PR TITLE
E-548 fix: replace 'regular password' with 'password'

### PR DESCRIPTION
**Pull request by ifiri**

### CODE REVIEW

**Comment by ifiri** [comment]
@dudiq ready for review. No `regular password`s in vault.

**Comment by dudiq** [comment]
@lamartire ready for approve

**Comment by lamartire** [comment]
@dudiq, @ifiri does this task mean only locales? Or we should rename all related abstractions too?

image

**Comment by dudiq** [comment]
@lamartire just locales only, because backend have `regular` entry points, 
no need to split them in our code

**Comment by lamartire** [comment]
@dudiq then approved

**Comment by dudiq** [comment]
@kazurus ready

**Pull request merged**
